//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace invenman
{
    public partial class BookingCreate
    {
        protected global::System.Web.UI.WebControls.Label lblMode;
        protected global::System.Web.UI.WebControls.ValidationSummary vsBooking;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlClient;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvClient;
        protected global::System.Web.UI.WebControls.DropDownList ddlAttraction;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAttraction;
        protected global::System.Web.UI.WebControls.TextBox txtTourDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTourDate;
        protected global::System.Web.UI.WebControls.TextBox txtPartySize;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPartySize;
        protected global::System.Web.UI.WebControls.RangeValidator rvPartySize;
        protected global::System.Web.UI.WebControls.TextBox txtTotalAmount;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTotalAmount;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revTotalAmount;
        protected global::System.Web.UI.WebControls.Label lblClientAmountNote;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlBookingStatus;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.HyperLink lnkViewBookings;
    }
}
