//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invenman
{
    public partial class BookingAssignTransportation
    {
        protected global::System.Web.UI.WebControls.Label lblMode;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlPlanningTools;
        protected global::System.Web.UI.WebControls.Button btnAutoPlan;
        protected global::System.Web.UI.WebControls.Label lblPlanSummary;
        protected global::System.Web.UI.WebControls.GridView gvBookings;
        protected global::System.Web.UI.WebControls.Panel pnlStaffEditor;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedBookingId;
        protected global::System.Web.UI.WebControls.DropDownList ddlTransportProvider;
        protected global::System.Web.UI.WebControls.TextBox txtPickupLocation;
        protected global::System.Web.UI.WebControls.TextBox txtPickupDate;
        protected global::System.Web.UI.WebControls.TextBox txtPickupTime;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnSaveAssignment;
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}
