//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace invenman
{
    public partial class PaymentRecord
    {
        protected global::System.Web.UI.WebControls.Label lblMode;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlBooking;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentMethod;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAmount;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revAmount;
        protected global::System.Web.UI.WebControls.TextBox txtTransactionReference;
        protected global::System.Web.UI.WebControls.Panel pnlInstructions;
        protected global::System.Web.UI.WebControls.Label lblInstructions;
        protected global::System.Web.UI.WebControls.Button btnPay;
    }
}
